### ISSUE TITLE
你们对我的新主题有什么看法

### ISSUE THREAD

**Issue by ice1000** [ice1000/ice1000.github.io#17]

**Comment by mslxl** [comment]
新换的 feed.xml 没问题吗?

我这边用 FeedReader 点链接直接就 404 了。

[feed.xml](http://ice1000.org/feed.xml)　里的 link 和 guid 节点都多了一道 `/`　，而且 `http://` 变成了 `http:/`

FeedReader和Feedly 会把 `http:/ice1000.org//2018/03/15/StackOverflowNonWaterAnswers/` 解析为 `http://ice1000.org/ice1000.org//2018/03/15/StackOverflowNonWaterAnswers/` ( 浏览器没事...)

```xml
<item>
        <title>**</title>
        <description>**</description>
        <pubDate>Thu, 15 Mar 2018 00:00:00 +0000</pubDate>
        <link>http:/ice1000.org//2018/03/15/StackOverflowNonWaterAnswers/</link>
        <guid isPermaLink="true">http:/ice1000.org//2018/03/15/StackOverflowNonWaterAnswers/</guid>
        <category>Misc</category>
        <category>Misc</category>
</item>

```

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/37874215-ab7c0600-305d-11e8-8c72-91c8b895f9ce.png)

本地的没问题啊。。。

**Comment by ice1000** [comment]
让我来好好研究一下这是什么原理，嗯。。

**Comment by ice1000** [comment]
搞懂了，是`_config.yml`的问题，现在已经修复了

**Comment by duangsuse** [comment]
前段水平不错（逃跑）
比我的好很多....
