### ISSUE TITLE
category c++

### ISSUE THREAD

**Issue by cstarc** [ice1000/ice1000.github.io#2]
为什么不能分一个c++的类，难道不能用+号

**Comment by ice1000** [comment]
因为我不写C++

**Comment by cstarc** [comment]
我的意思是我分了c++类，但不行，好像有+就不行，其它可以，这是为什么？

**Comment by ice1000** [comment]
估计是运算符被转义了，毕竟这个博客系统是基于Rails的，博客内容其实都是超级文本了，更何况是在元数据里面写。
建议改成C with classes或者C plus plus

**Comment by cstarc** [comment]
嗯，thank you
