### ISSUE TITLE
求评论功能

### ISSUE THREAD

**Issue by Ruanxingzhi** [ice1000/ice1000.github.io#3]
求上线评论功能。

**Comment by cdkd321** [comment]
同求！

**Comment by ice1000** [comment]
。。。。。

**Comment by ice1000** [comment]
挖坟满分，但是因为 http://ice1000.org/2017/09/20/AddedVisitCounting/ 里提到的理由不想加。
我部分文章会转载到知乎，你们可以使用知乎的评论区。

**Comment by ice1000** [comment]
我好像改变注意了。

**Comment by ice1000** [comment]
评论功能已添加。使用了 https://github.com/gioditalia/jekyll-comments-over-github/ 。

**Comment by ice1000** [comment]
为什么没有人来评论？ @Ruanxingzhi @cdkd321 @Ray-Eldath @thautwarm

**Comment by XIAOMING-QIN** [comment]
签到，来自知乎晓明

**Comment by cdkd321** [comment]
不能为了回复而回复嘛






在 2017-11-14 10:05:12，"Tesla Ice Zhang" <notifications@github.com> 写道：


评论功能已添加。使用了 https://github.com/gioditalia/jekyll-comments-over-github/ 。

**Comment by thautwarm** [comment]
啊...

**Comment by thautwarm** [comment]
我是爱你的。

**Comment by ice1000** [comment]
噗【
