### ISSUE TITLE
首页(index.html)没有rss的订阅链接

### ISSUE THREAD

**Issue by lmmsoft** [ice1000/ice1000.github.io#30]
首页(index.html)没放rss的链接，导致第三方订阅服务不能自动发现，还以为没有rss呢，直到看了about才找到，建议首页甚至每篇文章里都放rss链接

**Comment by ice1000** [comment]
emm 是的，我才发现。
谢谢提醒，会立即修复。

**Comment by lmmsoft** [comment]
赞效率！

**Comment by ice1000** [comment]
已经很慢了，拖了一天……
