### ISSUE TITLE
关于您博客 DNS 记录的建议

### ISSUE THREAD

**Issue by outloudvi** [ice1000/ice1000.github.io#31]
看到您的博客顶级域（apex）记录上只有一条 GitHub Pages 的 A 记录 IP：
```
$ dig ice1000.org +short
185.199.108.153
```
可能刚好在我访问您的博客时，GitHub 的 185.199.108.153 服务器出现问题，导致您的博客无法通过 ice1000.org 访问（[17ce 的测试结果](http://www.17ce.com/site/http/20181216_86f61b70012e11e9b68a91103989addb:1.html)），不过通过 www.ice1000.org 访问没有问题（看来 GitHub Pages 的其它 IP 正常）。考虑到 GitHub [不建议在顶级域上面写 CNAME](https://help.github.com/articles/setting-up-an-apex-domain/)，建议您将 GitHub Pages 所述的[四个 IP 地址](https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider)均添加到您的顶级域名 A 记录中，以提升您的博客的可连接性。

**Comment by ice1000** [comment]
我怎么记得四个都加了
不过还是让小可爱检查一下@Glavo
