### ISSUE TITLE
在想，是不是可以用 commit 底下可以留言的機制做留言板

### ISSUE THREAD

**Issue by mudream4869** [ice1000/ice1000.github.io#33]
不確定這樣會不會比較好就是，要不然有點難連結回去？

* ~~可能可以在網頁端抓留言？~~
* 1 個 commit 對應一個 blog 更新
* blog 更新的話留言會被洗掉

**Comment by ice1000** [comment]
我还可以一个commit改好几个文章，怎么办……

**Comment by ice1000** [comment]
Closing as no answer and being stale
