### ISSUE TITLE
您好, 我想观看您的一篇关于Agda中rewrite的文章

### ISSUE THREAD

**Issue by samuelUniversal** [ice1000/ice1000.github.io#39]
我最近在学plfa, 在第二章看到rewrite, 略感奇怪, 在知乎上看到您有一篇相关的文章, 故请求一看.

**Comment by ice1000** [comment]
????

are you asking me to write one or are you looking for a link?

(I don't have a Chinese input method right now, sry)

**Comment by ice1000** [comment]
Is it this one?

https://ice1000.org/2017/11-09-ProofInAgda5.html

**Comment by samuelUniversal** [comment]
谢谢您的回复, 我想请求的是这个回答上的.[“关于Agda的：关于Agda的rewrite（中文）”](https://www.zhihu.com/question/287689646/answer/457393070)

**Comment by samuelUniversal** [comment]
我先看一下从三到四

**Comment by ice1000** [comment]
> 谢谢您的回复, 我想请求的是这个回答上的.[“关于Agda的：关于Agda的rewrite（中文）”](https://www.zhihu.com/question/287689646/answer/457393070)

Then I was giving you the correct link. I don't recommend reading it though, it's of low quality from my present point of view. I apologize.

**Comment by samuelUniversal** [comment]
了解, 非常感谢您!
