### ISSUE TITLE
Maybe a typo in CuttMltt.lagda

### ISSUE THREAD

**Issue by anqurvanillapy** [ice1000/ice1000.github.io#40]
https://github.com/ice1000/ice1000.github.io/blob/master/_posts/en/2019-4-21-CuttMltt.lagda.md

In the Cubical Model section, the proof of `trans`:

```agda
 trans : {a b c : A} → a ≡ b → b ≡ c → a ≡ c
 trans p q i = hfill (λ { j (i = i0) → p i; j (i = i1) → q j}) (inS {- this -} (p i)) i
```

The `inS` is directed to `cubical`'s `inc`.

**Comment by ice1000** [comment]
This is not correct. What I've imported is `Cubical.Core.Everything`, which re-export `Cubical.Core.Primitive`, which does this:

```agda
open import Agda.Builtin.Cubical.Sub public
  renaming ( inc to inS
           ; primSubOut to outS
           )
```

The module:

https://ice1000.org/lagda/Cubical.Core.Primitives.html

**Comment by anqurvanillapy** [comment]
ahh stupid questoin
