### ISSUE TITLE
Blog "New blog structure &...": disambiguate word "ML"

### ISSUE THREAD

**Issue by duangsuse** [ice1000/ice1000.github.io#41]
https://github.com/ice1000/ice1000.github.io/blob/ab383511bc7604e70ecbddf12c4a0dd9cbd99907/_posts/en/2019-10-27-NewBlogStructure.md#L70

> PL, **ML**, Compilers, Security, mysterious language features,
Graphics, ...

:point_up_2: ML could be refer to the "[Meta Language](https://en.wikipedia.org/wiki/ML_(programming_language))" and "machine learning", what does it mean here?

And... Maybe you can rearrange terminologies, to increase the readability.

> PL, Compilers, mysterious language features, ML, Graphics, Security, ...

**Comment by duangsuse** [comment]
这里稍微不按规矩办事一点，说句题外话，下面我大致的意思：『有的东西还是讲清楚的一点好』。

当然，看冰封哥博客的人都是正常人，他们都肯定能明白上面的 PL 后面跟着的 ML 一定是 Machine Learning 的缩写，因为如果是 ML 语言的意思，那就已经包好在前面的 PL 里了。

这（不写明一些和标题无关的东西）其实也根本不是严谨与否的问题，当然我有点类似吹毛求疵。

不过我还是很在意啊，好像冰封之前就不太喜欢改自己博客的样子，下面我提的是你之前 CN 的博文，也算是代表几年前你的风格……

1. https://github.com/ice1000/ice1000.github.io/blob/master/_posts/cn/Lisp/2017-3-10-DifferenceBetweenMeAndDragonBook.md#L165

<details>
<summary>Details</summary>

>但是我还有一个费解的地方，就是我问灰灰：
>
>    lexical scoping 是不是编译的时候解析每个 identifier 所指代的变量，然后事先区分好
>
>灰灰说不是，我觉得比较费解嗯。。等我解决了再写篇文章。

</details>

如果说冰封很长一段时间都没理解，所以即便问题解决了也写不出文章，后来想再改/再写文章也被搁置了，为什么不试着在以后 PLT 的文章里简要讲一下，再回来加个链接呢？我作为一个读者就这篇文章而言，看到这种一直没定义的知识引用，太难了。（虽然你会吐嘈我就是写了，也看不懂QAQ）

如果冰封实在没时间再讲了，后来使用到那篇我觉得写得堪比 [Hello, declarative world](https://codon.com/hello-declarative-world) 一样优秀的 [数学符号下的编程谎言 (1) 数据编码](https://anqurvanillapy.github.io/?p=lies-about-programming-languages-in-mathematical-notations-1#$\lambda$-%E7%AE%97%E5%AD%90) 时也可以想想之前有没可以再加的 reference 啊。

2. https://github.com/ice1000/ice1000.github.io/blob/master/_posts/cn/Agda/2018-5-30-CoinductiveTypesInAgda.md#L20

<details>
<summary>Details</summary>

比较面向小学生的说法是，coinductive 就是在归纳的时候上升的，而 inductive 是在归纳的时候下降的。

比较面向工业界编程的说法是，coinductive 的数据类型是无穷的，inductive 是有穷的。
比如 `java.util.Collection` 就是 inductive 的， `java.util.Iterable` 就是 coinductive 的。

</details>

这里你名词解释的『面向小学生』也不够小学生啊…… 上升/下降，你之前讲了的偏序理论里也有这个名词啊，那它到底是什么东西上升、什么东西下降…… 好像说明白也不需要举一个以上的例子吧……

----
顺便弱弱地问一句…… 之前的 commit 历史都不要了么……

**Comment by ice1000** [comment]
> 顺便弱弱地问一句…… 之前的 commit 历史都不要了么……

不要了

其他等会回复

**Comment by ice1000** [comment]
> 不过我还是很在意啊，好像冰封之前就不太喜欢改自己博客的样子，下面我提的是你之前 CN 的博文，也算是代表几年前你的风格……

中文博客我准备删完了，现在写东西的风格也会改变，不会像以前那么傻 (本来是想改的，感觉太多改不过来了)，敬请期待

**Comment by ice1000** [comment]
> 『』 是传统中文版本的 “”，扩住一个词的情况下可以读作『所谓』或者不必读出

https://zhuanlan.zhihu.com/p/97193308

**Comment by ice1000** [comment]
> 这里你名词解释的『面向小学生』也不够小学生啊…… 上升/下降，你之前讲了的偏序理论里也有这个名词啊，那它到底是什么东西上升、什么东西下降…… 好像说明白也不需要举一个以上的例子吧……

你说的有道理，我觉得我可以删了我的 lagda 博客

**Comment by duangsuse** [comment]
> 中文博客我准备删完了

还是把链接去掉，或者不渲染、换 repo，archive 掉什么的算了吧，删完有点不利于别人找资料的感觉……

> zhuanlan.zhihu.com/p/97193308

嗯，这个引号问题的确有人会觉得好像会导致文风改变，但我没有强制要求别人怎么怎么样。
我现在用 Rime InputMethod，so 更习惯这种风格。

至于我上面，不是为了秀优越，只是想给你举出一个实例，什么叫做『详细写出』。

像上面一样写到大家都觉得脑残，或自己被当脑残，这就叫详细写出，一个极端的例子。

另外你引的那个是 _文本排版_ 上，虽说全角“”和方角括号『』本不该有区别，上面的文字我也只是看到了他表达对别人的这种区别厌恶的情感，这很难列出实际客观一点的比较和理由，但就 _语义表达_ 上，是有区别的，你看 [这个](https://duangsuse-valid-projects.github.io/Share/%E7%BB%9D%E5%8F%A5/%E7%BB%9D%E5%8F%A5%E8%AF%8D%E6%B3%95)。

（求不喷，我也是最近才开始，实际上我目前也就会点 partial application 抽象参数列表处理和 lexical scoping、闭包创建，unification（我管它叫归一化，不知道对不对）逻辑式反向计算在学，以及一些只会并查集(UnionFind)、Trie 树、Dijkstra 图算法和 Bitmap 简单处理的人所可能了解的东西，主要还是文法层面的浅层设计和非本质的直接翻译，如果喷的话也请冰封多多指教……）

还有一个例子可以看[这里](https://duangsuse-valid-projects.github.io/Share/Others/essay-kotlin-parser)，当然不能喷我没写复杂一点的算法啊…… 最近有点累。

> 你说的有道理，我觉得我可以删了我的 lagda 博客

……LAgda 的那个我没意见，的确已经相当容易阅读了。

但是你在文章里写得还不够详细…… 可不可以冒犯地请求一下，冰封能在这里把 coinducative 以及相关知识，在这个 issue 再复述一遍吗？如果你真的很懂的话，相信拨冗再讲一遍也不会使花的时间不值吧。

**Comment by duangsuse** [comment]
https://github.com/ice1000/ice1000.github.io/issues/28#issuecomment-569844731

呃，然后这个 comment 你给 react 了一个 confused，但却没指出对什么 confused…… 我理解的上升下降正确吗？

上面我也不是说你讲的 coinductive 很难理解或者我没搞懂（搞懂了我暂时也不会试用的），
只是我觉得，好像多把一个问题讲即便，会使得解释有利于别人理解一样。
