### ISSUE TITLE
Where is https://ice1000.org/lagda/ now

### ISSUE THREAD

**Issue by andreasabel** [ice1000/ice1000.github.io#45]
https://ice1000.org/lagda/ is linked from the Agda documentation, but seems to have been moved.

This is the remaining broken link in https://github.com/agda/agda/issues/3976.

**Comment by ice1000** [comment]
I think we shall remove it.

**Comment by ice1000** [comment]
Fixed via https://github.com/agda/agda/commit/9a938969b35901afb865f532993350f3dc612825
