### ISSUE TITLE
这，突然刷到你，敢问

### ISSUE THREAD

**Issue by TheBadZhang** [ice1000/ice1000.github.io#47]
以前有一个 ice1000.tech 是你的么？那为什么上面的文章没有搬到你新的博客呢？

**Comment by ice1000** [comment]
> 以前有一个 ice1000.tech 是你的么？

是

> 那为什么上面的文章没有搬到你新的博客呢？

https://ice1000.org/2019/10-27-NewBlogStructure.html

全删了，不保留低质量文章。中文 ⊊ 低质量。当然，我本地是有存档的。

**Comment by ice1000** [comment]
现在进行比较正常的创作，换了更多人能看懂的语言。感觉正常了许多。羞于承认自己曾经写过面向小白的内容。
