### ISSUE TITLE
Maybe a typo in post "2-dim syntax"

### ISSUE THREAD

**Issue by anqurvanillapy** [ice1000/ice1000.github.io#49]
> one-linear

I think it should be **one-liner**, the link it directs to contains a phrase "one-liner hack" for putting everything in a single line.  It seems it is nothing about the "linearity"

https://ice1000.org/2020/06-20-LayoutLexerInAlex.html

**Comment by anqurvanillapy** [comment]
Well, just found another issue, Python indentation can base on arbitrary spaces...

**Comment by ice1000** [comment]
Can you PR (so you get credits for this contribution)?
