### ISSUE TITLE
Typo in "Proving uniqueness of identity proofs from J"

### ISSUE THREAD

**Issue by re-xyr** [ice1000/ice1000.github.io#53]
> Well, we can also see some downsides of this definition of the equality type: it allows both sides to have the same type.

should be

> Well, we can also see some downsides of this definition of the equality type: it allows both sides **not** to have the same type *(or, **to have different types**)*.

---

Also, in

> So, the proof is cyclic.

I would suggest changing *cyclic* to *circular*.

---

By the way, why is Axiom K "stronger" than Axiom UIP?

**Comment by ice1000** [comment]
> By the way, why is Axiom K "stronger" than Axiom UIP?

I guess probably not. This should be a mistake.
